### ISSUE TITLE
'NoneType' object is not subscriptable 

### ISSUE THREAD

**Issue by Mohan-cloud** [costis94/bookcut#9]
Hey. I am running into this issue while running the command `bookcut book -b "White Fang" -a "Jack London"
`

> Searching for White fang by Jack london
Connected to: http://libgen.li/
'NoneType' object is not subscriptable
Downloading Link:NOT FOUND

**Comment by costis94** [comment]
Hey!

Thanks for your help! Indeed this was a serious bug that interrupted the proper function of BookCut.
The solution was very easy, just a small typo! But the main problem of the project is the absence of tests and a logger so that these problems do not arise. My main priority is to reorganize the code, and to resolve these issues!
